/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) source_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[24] = {9, 9, 0, 1, 2, 4, 5, 7, 8, 9, 10, 12, 3, 2, 1, 8, 0, 7, 8, 6, 5, 4, 2, 4};
static const casadi_int casadi_s3[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s4[52] = {14, 9, 0, 4, 8, 13, 17, 22, 26, 30, 34, 40, 3, 4, 5, 9, 3, 4, 5, 9, 0, 6, 7, 9, 10, 0, 6, 7, 9, 1, 4, 7, 11, 12, 1, 4, 7, 12, 5, 6, 8, 12, 5, 6, 8, 12, 2, 3, 8, 10, 11, 13};
static const casadi_int casadi_s5[71] = {126, 9, 0, 6, 13, 20, 26, 33, 39, 45, 52, 59, 27, 36, 40, 45, 51, 84, 28, 35, 37, 41, 46, 52, 83, 2, 56, 60, 65, 67, 82, 98, 3, 57, 61, 66, 68, 81, 13, 36, 40, 65, 67, 107, 115, 14, 37, 41, 66, 68, 114, 45, 51, 56, 60, 78, 113, 46, 52, 57, 61, 79, 80, 112, 26, 28, 35, 79, 80, 92, 103};

/* obj_f:(i0[9])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=-5.0000000000000000e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[0]? arg[0][3] : 0;
  a1=(a1*a2);
  a2=arg[0]? arg[0][1] : 0;
  a3=arg[0]? arg[0][2] : 0;
  a2=(a2*a3);
  a1=(a1-a2);
  a2=arg[0]? arg[0][8] : 0;
  a3=(a3*a2);
  a1=(a1+a3);
  a3=arg[0]? arg[0][4] : 0;
  a2=(a3*a2);
  a1=(a1-a2);
  a2=arg[0]? arg[0][7] : 0;
  a3=(a3*a2);
  a1=(a1+a3);
  a3=arg[0]? arg[0][5] : 0;
  a2=arg[0]? arg[0][6] : 0;
  a3=(a3*a2);
  a1=(a1-a3);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_f_grad:(i0[9])->(o0[9]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=-5.0000000000000000e-01;
  a1=arg[0]? arg[0][3] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=5.0000000000000000e-01;
  a2=arg[0]? arg[0][2] : 0;
  a3=(a1*a2);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[0]? arg[0][8] : 0;
  a4=(a0*a3);
  a5=arg[0]? arg[0][1] : 0;
  a5=(a1*a5);
  a4=(a4+a5);
  if (res[0]!=0) res[0][2]=a4;
  a4=arg[0]? arg[0][0] : 0;
  a4=(a0*a4);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[0]? arg[0][7] : 0;
  a4=(a0*a4);
  a3=(a1*a3);
  a4=(a4+a3);
  if (res[0]!=0) res[0][4]=a4;
  a4=arg[0]? arg[0][6] : 0;
  a4=(a1*a4);
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[0]? arg[0][5] : 0;
  a4=(a1*a4);
  if (res[0]!=0) res[0][6]=a4;
  a4=arg[0]? arg[0][4] : 0;
  a3=(a0*a4);
  if (res[0]!=0) res[0][7]=a3;
  a1=(a1*a4);
  a0=(a0*a2);
  a1=(a1+a0);
  if (res[0]!=0) res[0][8]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_grad_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_grad_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_grad_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_grad_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_grad_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_grad_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_grad_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_grad_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_grad_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_grad_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_grad_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_grad_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_grad_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_grad_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_f_hes:(i0[9])->(o0[9x9,12nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=-5.0000000000000000e-01;
  if (res[0]!=0) res[0][0]=a0;
  a1=5.0000000000000000e-01;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_hes_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_hes_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_hes_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_hes_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g:(i0[9])->(o0[14]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=1.;
  a1=arg[0]? arg[0][2] : 0;
  a2=casadi_sq(a1);
  a2=(a0-a2);
  a3=arg[0]? arg[0][3] : 0;
  a4=casadi_sq(a3);
  a2=(a2-a4);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0]? arg[0][4] : 0;
  a4=casadi_sq(a2);
  a4=(a0-a4);
  a5=arg[0]? arg[0][5] : 0;
  a6=casadi_sq(a5);
  a4=(a4-a6);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0]? arg[0][8] : 0;
  a6=casadi_sq(a4);
  a6=(a0-a6);
  if (res[0]!=0) res[0][2]=a6;
  a6=arg[0]? arg[0][0] : 0;
  a7=casadi_sq(a6);
  a7=(a0-a7);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a8-a4);
  a9=casadi_sq(a9);
  a7=(a7-a9);
  if (res[0]!=0) res[0][3]=a7;
  a7=(a6-a2);
  a7=casadi_sq(a7);
  a7=(a0-a7);
  a9=(a8-a5);
  a9=casadi_sq(a9);
  a7=(a7-a9);
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[0]? arg[0][6] : 0;
  a9=(a6-a7);
  a9=casadi_sq(a9);
  a9=(a0-a9);
  a10=arg[0]? arg[0][7] : 0;
  a11=(a8-a10);
  a11=casadi_sq(a11);
  a9=(a9-a11);
  if (res[0]!=0) res[0][5]=a9;
  a9=(a1-a7);
  a9=casadi_sq(a9);
  a9=(a0-a9);
  a11=(a3-a10);
  a11=casadi_sq(a11);
  a9=(a9-a11);
  if (res[0]!=0) res[0][6]=a9;
  a9=(a1-a2);
  a9=casadi_sq(a9);
  a9=(a0-a9);
  a11=(a3-a5);
  a11=casadi_sq(a11);
  a9=(a9-a11);
  if (res[0]!=0) res[0][7]=a9;
  a9=casadi_sq(a7);
  a0=(a0-a9);
  a9=(a10-a4);
  a9=casadi_sq(a9);
  a0=(a0-a9);
  if (res[0]!=0) res[0][8]=a0;
  a6=(a6*a3);
  a8=(a8*a1);
  a6=(a6-a8);
  if (res[0]!=0) res[0][9]=a6;
  a1=(a1*a4);
  if (res[0]!=0) res[0][10]=a1;
  a1=(a2*a4);
  a1=(-a1);
  if (res[0]!=0) res[0][11]=a1;
  a2=(a2*a10);
  a5=(a5*a7);
  a2=(a2-a5);
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g_jac:(i0[9])->(o0[14x9,40nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=(a0+a0);
  a1=(-a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][4] : 0;
  a2=(a0-a1);
  a2=(a2+a2);
  a3=(-a2);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[0]? arg[0][6] : 0;
  a4=(a0-a3);
  a4=(a4+a4);
  a5=(-a4);
  if (res[0]!=0) res[0][2]=a5;
  a5=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a5;
  a6=arg[0]? arg[0][1] : 0;
  a7=arg[0]? arg[0][8] : 0;
  a8=(a6-a7);
  a8=(a8+a8);
  a9=(-a8);
  if (res[0]!=0) res[0][4]=a9;
  a9=arg[0]? arg[0][5] : 0;
  a10=(a6-a9);
  a10=(a10+a10);
  a11=(-a10);
  if (res[0]!=0) res[0][5]=a11;
  a11=arg[0]? arg[0][7] : 0;
  a12=(a6-a11);
  a12=(a12+a12);
  a13=(-a12);
  if (res[0]!=0) res[0][6]=a13;
  a13=arg[0]? arg[0][2] : 0;
  a14=(-a13);
  if (res[0]!=0) res[0][7]=a14;
  a14=(a13+a13);
  a14=(-a14);
  if (res[0]!=0) res[0][8]=a14;
  a14=(a13-a3);
  a14=(a14+a14);
  a15=(-a14);
  if (res[0]!=0) res[0][9]=a15;
  a15=(a13-a1);
  a15=(a15+a15);
  a16=(-a15);
  if (res[0]!=0) res[0][10]=a16;
  a6=(-a6);
  if (res[0]!=0) res[0][11]=a6;
  if (res[0]!=0) res[0][12]=a7;
  a6=(a5+a5);
  a6=(-a6);
  if (res[0]!=0) res[0][13]=a6;
  a6=(a5-a11);
  a6=(a6+a6);
  a16=(-a6);
  if (res[0]!=0) res[0][14]=a16;
  a5=(a5-a9);
  a5=(a5+a5);
  a16=(-a5);
  if (res[0]!=0) res[0][15]=a16;
  if (res[0]!=0) res[0][16]=a0;
  a0=(a1+a1);
  a0=(-a0);
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a15;
  a15=(-a7);
  if (res[0]!=0) res[0][20]=a15;
  if (res[0]!=0) res[0][21]=a11;
  a15=(a9+a9);
  a15=(-a15);
  if (res[0]!=0) res[0][22]=a15;
  if (res[0]!=0) res[0][23]=a10;
  if (res[0]!=0) res[0][24]=a5;
  a5=(-a3);
  if (res[0]!=0) res[0][25]=a5;
  if (res[0]!=0) res[0][26]=a4;
  if (res[0]!=0) res[0][27]=a14;
  a3=(a3+a3);
  a3=(-a3);
  if (res[0]!=0) res[0][28]=a3;
  a9=(-a9);
  if (res[0]!=0) res[0][29]=a9;
  if (res[0]!=0) res[0][30]=a12;
  if (res[0]!=0) res[0][31]=a6;
  a11=(a11-a7);
  a11=(a11+a11);
  a6=(-a11);
  if (res[0]!=0) res[0][32]=a6;
  if (res[0]!=0) res[0][33]=a1;
  a7=(a7+a7);
  a7=(-a7);
  if (res[0]!=0) res[0][34]=a7;
  if (res[0]!=0) res[0][35]=a8;
  if (res[0]!=0) res[0][36]=a11;
  if (res[0]!=0) res[0][37]=a13;
  a1=(-a1);
  if (res[0]!=0) res[0][38]=a1;
  a1=1.;
  if (res[0]!=0) res[0][39]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g_hes:(i0[9])->(o0[126x9,59nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=-2.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=2.;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a1;
  a2=1.;
  if (res[0]!=0) res[0][5]=a2;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a1;
  a3=-1.;
  if (res[0]!=0) res[0][12]=a3;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a3;
  if (res[0]!=0) res[0][19]=a2;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a2;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a3;
  if (res[0]!=0) res[0][32]=a2;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a1;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a3;
  if (res[0]!=0) res[0][39]=a1;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a1;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a3;
  if (res[0]!=0) res[0][45]=a1;
  if (res[0]!=0) res[0][46]=a0;
  if (res[0]!=0) res[0][47]=a1;
  if (res[0]!=0) res[0][48]=a0;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a1;
  if (res[0]!=0) res[0][51]=a2;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a1;
  if (res[0]!=0) res[0][54]=a0;
  if (res[0]!=0) res[0][55]=a1;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a2;
  if (res[0]!=0) res[0][58]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_hes(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_hes_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_hes_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_hes_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_hes_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_hes_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_hes_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_hes_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_hes_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_hes_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_hes_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_hes_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_hes_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_hes_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_hes_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_hes_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* n_variables:()->(o0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=9.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int n_variables(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int n_variables_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int n_variables_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void n_variables_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int n_variables_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void n_variables_release(int mem) {
}

CASADI_SYMBOL_EXPORT void n_variables_incref(void) {
}

CASADI_SYMBOL_EXPORT void n_variables_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int n_variables_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int n_variables_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real n_variables_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* n_variables_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* n_variables_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* n_variables_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* n_variables_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int n_variables_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* n_constrains:()->(o0) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=14.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int n_constrains(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int n_constrains_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int n_constrains_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void n_constrains_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int n_constrains_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void n_constrains_release(int mem) {
}

CASADI_SYMBOL_EXPORT void n_constrains_incref(void) {
}

CASADI_SYMBOL_EXPORT void n_constrains_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int n_constrains_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int n_constrains_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real n_constrains_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* n_constrains_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* n_constrains_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* n_constrains_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* n_constrains_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int n_constrains_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g_jac_nze:()->(o0) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=40.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_nze_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_nze_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_nze_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_nze_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_nze_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_nze_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_jac_nze_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_nze_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_nze_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_nze_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_nze_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_f_hes_nze:()->(o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=25.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_nze_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_nze_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_nze_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_nze_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_nze_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_nze_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_hes_nze_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_nze_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_nze_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_nze_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_nze_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* x_l_casadi:()->(o0[9]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int x_l_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int x_l_casadi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int x_l_casadi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_l_casadi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int x_l_casadi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_l_casadi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void x_l_casadi_incref(void) {
}

CASADI_SYMBOL_EXPORT void x_l_casadi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x_l_casadi_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int x_l_casadi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real x_l_casadi_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_l_casadi_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_l_casadi_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_l_casadi_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_l_casadi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x_l_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* x_u_casadi:()->(o0[9]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int x_u_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int x_u_casadi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int x_u_casadi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_u_casadi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int x_u_casadi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_u_casadi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void x_u_casadi_incref(void) {
}

CASADI_SYMBOL_EXPORT void x_u_casadi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x_u_casadi_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int x_u_casadi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real x_u_casadi_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_u_casadi_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_u_casadi_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_u_casadi_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_u_casadi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x_u_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_l_casadi:()->(o0[14]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_l_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_l_casadi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_l_casadi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_l_casadi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_l_casadi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_l_casadi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_l_casadi_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_l_casadi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_l_casadi_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int g_l_casadi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_l_casadi_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_l_casadi_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_l_casadi_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_l_casadi_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_l_casadi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_l_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_u_casadi:()->(o0[14]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=2.0000000000000000e+19;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_u_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_u_casadi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_u_casadi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_u_casadi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_u_casadi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_u_casadi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_u_casadi_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_u_casadi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_u_casadi_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int g_u_casadi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_u_casadi_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_u_casadi_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_u_casadi_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_u_casadi_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_u_casadi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_u_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* x_start_point:()->(o0[9]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int x_start_point(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int x_start_point_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int x_start_point_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_start_point_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int x_start_point_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_start_point_release(int mem) {
}

CASADI_SYMBOL_EXPORT void x_start_point_incref(void) {
}

CASADI_SYMBOL_EXPORT void x_start_point_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x_start_point_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int x_start_point_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real x_start_point_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_start_point_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_start_point_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_start_point_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_start_point_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x_start_point_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
