/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) source_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[19] = {7, 7, 0, 1, 2, 3, 4, 5, 7, 9, 0, 1, 2, 3, 4, 5, 6, 5, 6};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[20] = {2, 7, 0, 2, 4, 6, 7, 8, 9, 10, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1};
static const casadi_int casadi_s5[18] = {14, 7, 0, 3, 6, 7, 8, 8, 8, 8, 0, 7, 8, 1, 7, 8, 9, 3};

/* obj_f:(i0[7])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[0]? arg[0][0] : 0;
  a1=10.;
  a0=(a0-a1);
  a0=casadi_sq(a0);
  a2=5.;
  a3=arg[0]? arg[0][1] : 0;
  a4=12.;
  a3=(a3-a4);
  a3=casadi_sq(a3);
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[0]? arg[0][2] : 0;
  a2=casadi_sq(a2);
  a2=casadi_sq(a2);
  a0=(a0+a2);
  a2=3.;
  a3=arg[0]? arg[0][3] : 0;
  a4=11.;
  a3=(a3-a4);
  a3=casadi_sq(a3);
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[0]? arg[0][4] : 0;
  a3=casadi_sq(a2);
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a2=(a1*a2);
  a0=(a0+a2);
  a2=7.;
  a3=arg[0]? arg[0][5] : 0;
  a4=casadi_sq(a3);
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[0]? arg[0][6] : 0;
  a4=casadi_sq(a2);
  a4=casadi_sq(a4);
  a0=(a0+a4);
  a4=4.;
  a4=(a4*a3);
  a4=(a4*a2);
  a0=(a0-a4);
  a1=(a1*a3);
  a0=(a0-a1);
  a1=8.;
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_f_grad:(i0[7])->(o0[7]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=arg[0]? arg[0][0] : 0;
  a1=10.;
  a0=(a0-a1);
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=5.;
  a2=arg[0]? arg[0][1] : 0;
  a3=12.;
  a2=(a2-a3);
  a2=(a2+a2);
  a0=(a0*a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a2=(a0+a0);
  a0=casadi_sq(a0);
  a0=(a0+a0);
  a2=(a2*a0);
  if (res[0]!=0) res[0][2]=a2;
  a2=3.;
  a0=arg[0]? arg[0][3] : 0;
  a3=11.;
  a0=(a0-a3);
  a0=(a0+a0);
  a2=(a2*a0);
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[0]? arg[0][4] : 0;
  a0=casadi_sq(a2);
  a3=(a2*a0);
  a3=(a3+a3);
  a1=(a1*a3);
  a0=(a0*a1);
  a3=(a2+a2);
  a2=(a2*a1);
  a3=(a3*a2);
  a0=(a0+a3);
  if (res[0]!=0) res[0][4]=a0;
  a0=-10.;
  a3=4.;
  a2=arg[0]? arg[0][6] : 0;
  a1=(a3*a2);
  a0=(a0-a1);
  a1=7.;
  a4=arg[0]? arg[0][5] : 0;
  a5=(a4+a4);
  a1=(a1*a5);
  a0=(a0+a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=-8.;
  a3=(a3*a4);
  a0=(a0-a3);
  a3=(a2+a2);
  a2=casadi_sq(a2);
  a2=(a2+a2);
  a3=(a3*a2);
  a0=(a0+a3);
  if (res[0]!=0) res[0][6]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_grad_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_grad_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_grad_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_grad_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_grad_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_grad_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_grad_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_grad_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_grad_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_grad_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_grad_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_grad_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_grad_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_grad_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_f_hes:(i0[7])->(o0[7x7,9nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  a1=10.;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][2] : 0;
  a3=casadi_sq(a2);
  a3=(a3+a3);
  a3=(a0*a3);
  a4=(a2+a2);
  a2=(a2+a2);
  a2=(a2+a2);
  a4=(a4*a2);
  a3=(a3+a4);
  if (res[0]!=0) res[0][2]=a3;
  a3=6.;
  if (res[0]!=0) res[0][3]=a3;
  a3=arg[0]? arg[0][4] : 0;
  a4=casadi_sq(a3);
  a2=(a3*a4);
  a2=(a2+a2);
  a2=(a1*a2);
  a5=(a3+a3);
  a6=(a2*a5);
  a5=(a3*a5);
  a5=(a4+a5);
  a5=(a5+a5);
  a1=(a1*a5);
  a4=(a4*a1);
  a6=(a6+a4);
  a4=(a3*a2);
  a4=(a0*a4);
  a5=(a3+a3);
  a3=(a3*a1);
  a2=(a2+a3);
  a5=(a5*a2);
  a4=(a4+a5);
  a6=(a6+a4);
  if (res[0]!=0) res[0][4]=a6;
  a6=14.;
  if (res[0]!=0) res[0][5]=a6;
  a6=-4.;
  if (res[0]!=0) res[0][6]=a6;
  if (res[0]!=0) res[0][7]=a6;
  a6=arg[0]? arg[0][6] : 0;
  a4=casadi_sq(a6);
  a4=(a4+a4);
  a0=(a0*a4);
  a4=(a6+a6);
  a6=(a6+a6);
  a6=(a6+a6);
  a4=(a4*a6);
  a0=(a0+a4);
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_hes_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_hes_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_hes_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_hes_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g:(i0[7])->(o0[2]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=2.;
  a1=arg[0]? arg[0][0] : 0;
  a2=casadi_sq(a1);
  a2=(a0*a2);
  a3=3.;
  a4=arg[0]? arg[0][1] : 0;
  a5=casadi_sq(a4);
  a5=casadi_sq(a5);
  a5=(a3*a5);
  a2=(a2+a5);
  a5=arg[0]? arg[0][2] : 0;
  a2=(a2+a5);
  a6=4.;
  a7=arg[0]? arg[0][3] : 0;
  a7=casadi_sq(a7);
  a6=(a6*a7);
  a2=(a2+a6);
  a6=5.;
  a7=arg[0]? arg[0][4] : 0;
  a7=(a6*a7);
  a2=(a2+a7);
  if (res[0]!=0) res[0][0]=a2;
  a2=-4.;
  a7=casadi_sq(a1);
  a2=(a2*a7);
  a7=casadi_sq(a4);
  a2=(a2-a7);
  a3=(a3*a1);
  a3=(a3*a4);
  a2=(a2+a3);
  a5=casadi_sq(a5);
  a0=(a0*a5);
  a2=(a2-a0);
  a0=arg[0]? arg[0][5] : 0;
  a6=(a6*a0);
  a2=(a2-a6);
  a6=11.;
  a0=arg[0]? arg[0][6] : 0;
  a6=(a6*a0);
  a2=(a2+a6);
  if (res[0]!=0) res[0][1]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g_jac:(i0[7])->(o0[2x7,10nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=2.;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a1+a1);
  a0=(a0*a2);
  if (res[0]!=0) res[0][0]=a0;
  a0=3.;
  a2=arg[0]? arg[0][1] : 0;
  a3=(a0*a2);
  a4=-4.;
  a5=(a1+a1);
  a4=(a4*a5);
  a3=(a3+a4);
  if (res[0]!=0) res[0][1]=a3;
  a3=(a2+a2);
  a4=casadi_sq(a2);
  a4=(a4+a4);
  a4=(a0*a4);
  a3=(a3*a4);
  if (res[0]!=0) res[0][2]=a3;
  a0=(a0*a1);
  a2=(a2+a2);
  a0=(a0-a2);
  if (res[0]!=0) res[0][3]=a0;
  a0=1.;
  if (res[0]!=0) res[0][4]=a0;
  a0=-2.;
  a2=arg[0]? arg[0][2] : 0;
  a2=(a2+a2);
  a0=(a0*a2);
  if (res[0]!=0) res[0][5]=a0;
  a0=4.;
  a2=arg[0]? arg[0][3] : 0;
  a2=(a2+a2);
  a0=(a0*a2);
  if (res[0]!=0) res[0][6]=a0;
  a0=5.;
  if (res[0]!=0) res[0][7]=a0;
  a0=-5.;
  if (res[0]!=0) res[0][8]=a0;
  a0=11.;
  if (res[0]!=0) res[0][9]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g_hes:(i0[7])->(o0[14x7,8nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=4.;
  if (res[0]!=0) res[0][0]=a0;
  a0=-8.;
  if (res[0]!=0) res[0][1]=a0;
  a0=3.;
  if (res[0]!=0) res[0][2]=a0;
  a1=2.;
  a2=arg[0]? arg[0][1] : 0;
  a3=casadi_sq(a2);
  a3=(a3+a3);
  a3=(a0*a3);
  a1=(a1*a3);
  a3=(a2+a2);
  a2=(a2+a2);
  a2=(a2+a2);
  a2=(a0*a2);
  a3=(a3*a2);
  a1=(a1+a3);
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  a0=-2.;
  if (res[0]!=0) res[0][5]=a0;
  a0=-4.;
  if (res[0]!=0) res[0][6]=a0;
  a0=8.;
  if (res[0]!=0) res[0][7]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_hes(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_hes_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_hes_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_hes_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_hes_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_hes_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_hes_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_hes_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_hes_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_hes_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_hes_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_hes_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_hes_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_hes_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_hes_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_hes_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* n_variables:()->(o0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=7.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int n_variables(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int n_variables_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int n_variables_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void n_variables_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int n_variables_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void n_variables_release(int mem) {
}

CASADI_SYMBOL_EXPORT void n_variables_incref(void) {
}

CASADI_SYMBOL_EXPORT void n_variables_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int n_variables_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int n_variables_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real n_variables_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* n_variables_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* n_variables_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* n_variables_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* n_variables_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int n_variables_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* n_constrains:()->(o0) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int n_constrains(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int n_constrains_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int n_constrains_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void n_constrains_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int n_constrains_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void n_constrains_release(int mem) {
}

CASADI_SYMBOL_EXPORT void n_constrains_incref(void) {
}

CASADI_SYMBOL_EXPORT void n_constrains_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int n_constrains_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int n_constrains_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real n_constrains_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* n_constrains_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* n_constrains_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* n_constrains_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* n_constrains_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int n_constrains_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g_jac_nze:()->(o0) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=10.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_nze_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_nze_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_nze_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_nze_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_nze_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_nze_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_jac_nze_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_nze_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_nze_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_nze_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_nze_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_jac_nze_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_f_hes_nze:()->(o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=9.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_nze_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_nze_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_nze_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_nze_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_nze_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_nze_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_hes_nze_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_nze_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_nze_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_nze_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_nze_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_hes_nze_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* x_l_casadi:()->(o0[7]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=-5.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int x_l_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int x_l_casadi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int x_l_casadi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_l_casadi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int x_l_casadi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_l_casadi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void x_l_casadi_incref(void) {
}

CASADI_SYMBOL_EXPORT void x_l_casadi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x_l_casadi_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int x_l_casadi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real x_l_casadi_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_l_casadi_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_l_casadi_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_l_casadi_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_l_casadi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x_l_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* x_u_casadi:()->(o0[7]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=5.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int x_u_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int x_u_casadi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int x_u_casadi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_u_casadi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int x_u_casadi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_u_casadi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void x_u_casadi_incref(void) {
}

CASADI_SYMBOL_EXPORT void x_u_casadi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x_u_casadi_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int x_u_casadi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real x_u_casadi_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_u_casadi_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_u_casadi_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_u_casadi_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_u_casadi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x_u_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_l_casadi:()->(o0[2]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=127.;
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_l_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_l_casadi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_l_casadi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_l_casadi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_l_casadi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_l_casadi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_l_casadi_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_l_casadi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_l_casadi_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int g_l_casadi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_l_casadi_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_l_casadi_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_l_casadi_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_l_casadi_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_l_casadi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_l_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_u_casadi:()->(o0[2]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=127.;
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_u_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_u_casadi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_u_casadi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_u_casadi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_u_casadi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_u_casadi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_u_casadi_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_u_casadi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_u_casadi_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int g_u_casadi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_u_casadi_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_u_casadi_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_u_casadi_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_u_casadi_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_u_casadi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_u_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* x_start_point:()->(o0[7]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=2.;
  if (res[0]!=0) res[0][1]=a1;
  a1=0.;
  if (res[0]!=0) res[0][2]=a1;
  a2=4.;
  if (res[0]!=0) res[0][3]=a2;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int x_start_point(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int x_start_point_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int x_start_point_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_start_point_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int x_start_point_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_start_point_release(int mem) {
}

CASADI_SYMBOL_EXPORT void x_start_point_incref(void) {
}

CASADI_SYMBOL_EXPORT void x_start_point_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x_start_point_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int x_start_point_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real x_start_point_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_start_point_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_start_point_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_start_point_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_start_point_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x_start_point_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
