/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_functions_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[21] = {5, 5, 0, 2, 5, 8, 11, 13, 0, 1, 0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[16] = {3, 5, 0, 2, 4, 6, 7, 8, 0, 2, 0, 1, 0, 1, 1, 2};
static const casadi_int casadi_s5[13] = {15, 5, 0, 1, 2, 4, 4, 5, 14, 1, 2, 7, 10};

/* obj_f:(i0[5])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[0]? arg[0][0] : 0;
  a1=1.;
  a1=(a0-a1);
  a1=casadi_sq(a1);
  a2=arg[0]? arg[0][1] : 0;
  a0=(a0-a2);
  a0=casadi_sq(a0);
  a1=(a1+a0);
  a0=arg[0]? arg[0][2] : 0;
  a2=(a2-a0);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[0]? arg[0][3] : 0;
  a0=(a0-a2);
  a0=casadi_sq(a0);
  a0=casadi_sq(a0);
  a1=(a1+a0);
  a0=arg[0]? arg[0][4] : 0;
  a2=(a2-a0);
  a2=casadi_sq(a2);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_f_grad:(i0[5])->(o0[5]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[0]? arg[0][1] : 0;
  a2=(a0-a1);
  a2=(a2+a2);
  a3=1.;
  a0=(a0-a3);
  a0=(a0+a0);
  a0=(a2+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a1=(a1-a0);
  a1=(a1+a1);
  a2=(a1-a2);
  if (res[0]!=0) res[0][1]=a2;
  a2=arg[0]? arg[0][3] : 0;
  a0=(a0-a2);
  a3=(a0+a0);
  a0=casadi_sq(a0);
  a0=(a0+a0);
  a3=(a3*a0);
  a1=(a3-a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[0]? arg[0][4] : 0;
  a2=(a2-a1);
  a1=(a2+a2);
  a2=casadi_sq(a2);
  a2=(a2+a2);
  a1=(a1*a2);
  a3=(a1-a3);
  if (res[0]!=0) res[0][3]=a3;
  a1=(-a1);
  if (res[0]!=0) res[0][4]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_grad_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_grad_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_grad_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_grad_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_grad_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_grad_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_grad_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_grad_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_grad_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_grad_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_grad_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_grad_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_grad_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_grad_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_f_hes:(i0[5])->(o0[5x5,13nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=4.;
  if (res[0]!=0) res[0][0]=a0;
  a1=-2.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  a0=2.;
  a2=arg[0]? arg[0][2] : 0;
  a3=arg[0]? arg[0][3] : 0;
  a2=(a2-a3);
  a4=casadi_sq(a2);
  a4=(a4+a4);
  a5=(a0*a4);
  a6=(a2+a2);
  a2=(a2+a2);
  a7=(a2+a2);
  a7=(a6*a7);
  a5=(a5+a7);
  a7=(a5+a0);
  if (res[0]!=0) res[0][6]=a7;
  a5=(-a5);
  if (res[0]!=0) res[0][7]=a5;
  if (res[0]!=0) res[0][8]=a5;
  a5=arg[0]? arg[0][4] : 0;
  a3=(a3-a5);
  a5=casadi_sq(a3);
  a5=(a5+a5);
  a0=(a0*a5);
  a7=(a3+a3);
  a3=(a3+a3);
  a8=(a3+a3);
  a8=(a7*a8);
  a0=(a0+a8);
  a4=(a1*a4);
  a2=(a2+a2);
  a6=(a6*a2);
  a4=(a4-a6);
  a0=(a0-a4);
  if (res[0]!=0) res[0][9]=a0;
  a1=(a1*a5);
  a3=(a3+a3);
  a7=(a7*a3);
  a1=(a1-a7);
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  a1=(-a1);
  if (res[0]!=0) res[0][12]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_f_hes_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_f_hes_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_f_hes_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_f_hes_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_f_hes_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int obj_f_hes_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_f_hes_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_f_hes_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_f_hes_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_f_hes_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g:(i0[5])->(o0[3]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[0]? arg[0][1] : 0;
  a2=casadi_sq(a1);
  a2=(a0+a2);
  a3=arg[0]? arg[0][2] : 0;
  a4=casadi_sq(a3);
  a4=(a3*a4);
  a2=(a2+a4);
  if (res[0]!=0) res[0][0]=a2;
  a3=casadi_sq(a3);
  a1=(a1-a3);
  a3=arg[0]? arg[0][3] : 0;
  a1=(a1+a3);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][4] : 0;
  a0=(a0*a1);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g_jac:(i0[5])->(o0[3x5,8nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][1] : 0;
  a1=(a1+a1);
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a0;
  a1=arg[0]? arg[0][2] : 0;
  a2=casadi_sq(a1);
  a3=(a1+a1);
  a3=(a1*a3);
  a2=(a2+a3);
  if (res[0]!=0) res[0][4]=a2;
  a1=(a1+a1);
  a1=(-a1);
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][7]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_jac_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* con_g_hes:(i0[5])->(o0[15x5,5nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=2.;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][2] : 0;
  a3=(a2+a2);
  a4=(a2+a2);
  a1=(a1*a2);
  a4=(a4+a1);
  a3=(a3+a4);
  if (res[0]!=0) res[0][2]=a3;
  a3=-2.;
  if (res[0]!=0) res[0][3]=a3;
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_hes(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int con_g_hes_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int con_g_hes_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_hes_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int con_g_hes_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void con_g_hes_release(int mem) {
}

CASADI_SYMBOL_EXPORT void con_g_hes_incref(void) {
}

CASADI_SYMBOL_EXPORT void con_g_hes_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int con_g_hes_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int con_g_hes_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real con_g_hes_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_hes_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* con_g_hes_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_hes_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* con_g_hes_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int con_g_hes_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
